### ISSUE TITLE
GTF file does not exist

### ISSUE THREAD

**Issue by mgalland** [KoesGroup/Snakemake_hisat-DESeq#10]
When running the Snakefile (commit 37d9256), I get an error because a link does not exist.
@tijsbliek could you fix this?  

The link that does not exist:
`ftp://ftp.solgenomics.net/genomes/Petunia_axillaris/annotation/Petunia_axillaris_v1.6.2_CDS.gtf`

**Comment by tijsbliek** [comment]
Fixed the link.

I now got an error in the DESeq script.
