### ISSUE TITLE
some update on the branch develop!

### ISSUE THREAD

**Issue by JihedC** [KoesGroup/Snakemake_hisat-DESeq#26]
Hi guys, 
I have tried to run the pipeline from the branch `develop` to see if it worked, I removed one of the Conda environment from the Snakefile that didn't exist. From that the dry run was working but when I tried to run with the subsamples, I have got this error :
```
[Thu Jul  4 22:05:31 2019]
Job 4: mapping reads to genome to bam files.

Job counts:
	count	jobs
	1	hisat_mapping
	1
dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /anaconda3/envs/tijs/bin/samtools
  Reason: image not found
(ERR): hisat2-align died with signal 13 (PIPE)
```
The problem seems to be an environment issue, but the rule that use a 'run' doesn't accept the hisat2/samtools environment I tried to create. 
Do you have an idea how to solve this?

Cheers,

Jihed

**Comment by JihedC** [comment]
The issue was on my laptop

**Comment by mgalland** [comment]
When you run a rule with the command "run", it cannot be combined with a conda rule attribute. So you'd have to have that software in your environment.  

The library issue that you have has to do with the samtools version (the 1.9.0 works fine). Sometimes, it can also come from a channel issue. Whether you install some dependencies from `conda-forge` or from `defaults` makes a difference.

We'll get back to it on Monday together with Tijs. I'd suggest to start again from the ` master`  and try to integrate some of the changes that Tijs made on the ` develop`  branch.

**Comment by JihedC** [comment]
I have tried the master branch and it seems to work properly to get the count file
